services:
  - type: web
    name: urlshorter-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXT_PUBLIC_FRONTEND_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
        